package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0057bd)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF6e9fff)
val md_theme_light_onPrimaryContainer = Color(0xFF002150)
val md_theme_light_secondary = Color(0xFF006668)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF0bfbff)
val md_theme_light_onSecondaryContainer = Color(0xFF005b5d)
val md_theme_light_tertiary = Color(0xFF00637f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF70d6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF00485d)
val md_theme_light_error = Color(0xFFb31b25)
val md_theme_light_errorContainer = Color(0xFFfb5151)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF570008)
val md_theme_light_background = Color(0xFFf3f7fb)
val md_theme_light_onBackground = Color(0xFF2a2f32)
val md_theme_light_surface = Color(0xFFf3f7fb)
val md_theme_light_onSurface = Color(0xFF2a2f32)
val md_theme_light_surfaceVariant = Color(0xFFd7dee3)
val md_theme_light_onSurfaceVariant = Color(0xFF575c60)
val md_theme_light_outline = Color(0xFF73777b)
val md_theme_light_inverseOnSurface = Color(0xFF999da1)
val md_theme_light_inverseSurface = Color(0xFF0a0f12)
val md_theme_light_inversePrimary = Color(0xFF4d8eff)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0057bd)
val md_theme_light_outlineVariant = Color(0xFFa9aeb1)
val md_theme_light_scrim = Color(0xFF000000)

val seed = Color(0xFF0057bd)
